# Workflow name
name: 'Install Dependencies'

# Event for the workflow
on:
  workflow_call

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# List of jobs
jobs:
  install:
    name: Yarn Install
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install
        # 👇 Install dependencies
        run: yarn