# Workflow name
name: 'Code Quality'

# Event for the workflow
on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# List of jobs
jobs:
  lint:
    name: Lint
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        # 👇 Install dependencies
        run: pnpm install
        # 👇 Lint
      - name: Lint
        run: pnpm lint
      - name: Typescript
        run: pnpm tsc
  test:
    name: Test
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        # 👇 Install dependencies
        run: pnpm istall
        # 👇 Lint and test code
      - name: Test Coverage
        run: pnpm test:coverage
      - name: Coverage
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

