# Workflow name
name: 'Code Quality'

# Event for the workflow
on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# List of jobs
jobs:
  lint:
    name: Lint
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        # 👇 Install dependencies
        run: yarn
        # 👇 Lint
      - name: Lint
        run: yarn lint
  test:
    name: Test
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        # 👇 Install dependencies
        run: yarn
        # 👇 Lint and test code
      - name: Test Storybook
        run: yarn storybook:test:coverage
      - name: Test Vite
        run: yarn test:coverage
      - name: Coverage
        uses: codecov/codecov-action@v3
          env: CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

